const ACTIONS = {
  SET_THEME: 'SET_THEME',
  TOGGLE_FAVORITE: 'TOGGLE_FAVORITE',
  SET_TERM: 'SET_TERM',
  SET_RESULTS: 'SET_RESULTS',
  SET_EMOJIS: 'SET_EMOJIS',
  SET_FAVORITES: 'SET_FAVORITES'
}

export default ACTIONS;