const ACTIONS = {
  SET_THEME: 'SET_THEME',
  TOGGLE_FAVORITE: 'TOGGLE_FAVORITE',
  SET_TERM: 'SET_TERM',
  SET_RESULTS: 'SET_RESULTS',
  SET_LOADING: 'SET_LOADING',
  SET_FAVORITES: 'SET_FAVORITES',
  CLEAR_RESULTS: 'CLEAR_RESULTS'
}

export default ACTIONS;